name: streamlit_app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - pip
  - pip:
      - streamlit
      - plotly
      - scikit-learn
      - matplotlib
      - requests==2.31.0
      - pyarrow==15.0.0
      - pandas==2.2.0